source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/yusuga/Specs.git'

platform :ios, '7.0'
pod 'Realm', '0.88.0'
pod 'CocoaLumberjack', '~> 2.0.0-rc'

pod 'YSCocoaLumberjackHelper'