platform :ios, '7.0'

target 'YSRealmStoreExample' do
  pod 'Realm', '~> 1.0'
  
  pod 'LumberjackLauncher'
  
  target 'YSRealmStoreExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
